"""
Loader for the unified "optimized framability" dataset.

Single source of truth used by all plotting scripts so that the optimized
framability shown is consistent across the two-qubit, six-qubit (2x3),
and any future scans.

The unified array lives at `results/optimized_framability_unified.npy` and
is generated by `unify_optimized_framability.py`.  It has shape (n_g, n_gp)
on a uniform `gamma_step` grid starting at 0; cells with no data are NaN.
A companion `..._meta.npz` stores `gamma_step`, `n_g`, `n_gp`, and a list of
source descriptors.
"""

from __future__ import annotations

from pathlib import Path
from typing import Tuple

import numpy as np


DEFAULT_PATH = Path("results/optimized_framability_unified.npy")
DEFAULT_META = Path("results/optimized_framability_unified_meta.npz")


def load(path: Path | str = DEFAULT_PATH,
         meta_path: Path | str | None = None) -> Tuple[np.ndarray, float]:
    """Return (unified_fra, gamma_step).

    `unified_fra` has shape (n_g, n_gp); NaN where no source covered the cell.
    """
    p = Path(path)
    if not p.is_file():
        raise FileNotFoundError(
            f"Unified optimized framability not found at {p}. "
            f"Run `python unify_optimized_framability.py` first."
        )
    arr = np.load(p)
    mp = Path(meta_path) if meta_path is not None else \
        p.with_name(p.stem + "_meta.npz")
    if mp.is_file():
        meta = np.load(mp, allow_pickle=True)
        gs = float(meta["gamma_step"])
    else:
        gs = 0.2  # fallback: default used by all current scans
    return arr, gs


def crop(arr: np.ndarray, n_g: int, n_gp: int) -> np.ndarray:
    """Crop the unified grid to the (n_g, n_gp) sub-grid anchored at origin."""
    if arr.shape[0] < n_g or arr.shape[1] < n_gp:
        raise ValueError(
            f"Unified grid {arr.shape} smaller than requested ({n_g},{n_gp})."
        )
    return arr[:n_g, :n_gp]
