r"""
Emit a hand-verifiable .tex derivation of the framability of one trotter-scan
point, for a chosen model and (x, y) = (p1, p2) grid location.

The document lays out, with every matrix printed explicitly:

    S            the optimised single-qubit frame            (4 x d_ext_single)
    D = S (x) S  the two-qubit dictionary                    (16 x d_ext)
    G            the 16x16 real Trotter gate expm(L dt)      (16 x 16)
    B = G^T D    the frame images whose atomic norms define  (16 x d_ext)
                 the framability   (matches _framability_lp: Y = gate.real^T D)

and then the explicit framability computation:

    framability = max_j  gamma_D(B_{:,j}),
    gamma_D(b)  = min { ||u||_1 : D u = b }   (Minkowski gauge / atomic norm),

printed as a per-column table of the minimal l1 norms, with the binding column
j* highlighted, its optimal coefficient vector u* written out, and the identity
D u* = B_{:,j*} with ||u*||_1 = framability shown so the value can be re-derived
by hand.

The frame S and gate are taken from the stored (confirmed) npz at the grid point
nearest to the requested (x, y); the framability is recomputed here from scratch
with an independent per-column HiGHS solve, so this file is a genuine external
check on the stored opt_fra value.

    python scripts/export_framability_tex.py --model model3 --x 0.8 --y 0.8 --de 6
    python scripts/export_framability_tex.py --model model5 --x 2.0 --y 4.8 --de 4 \
        --out framability_model5_2.0_4.8.tex
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from scipy.optimize import linprog

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from trotter_lindbladian_scan import MODELS, bond_trotter_gate
from dissipative_PT import _kron_power, spectral_floor

FMT = '{:+.4f}'


def bmatrix(M, fmt=FMT):
    rows = [' & '.join(fmt.format(v) for v in np.atleast_1d(row)) for row in M]
    return '\\begin{bmatrix}\n' + ' \\\\\n'.join(rows) + '\n\\end{bmatrix}'


def colvec(v, fmt=FMT):
    return '\\begin{bmatrix}\n' + ' \\\\\n'.join(fmt.format(x) for x in v) \
        + '\n\\end{bmatrix}'


def column_gauge(D, b):
    """min ||u||_1 s.t. D u = b, via HiGHS (presolve on). Returns (value, u)."""
    n, de = D.shape
    c = np.concatenate([np.zeros(de), np.ones(de)])
    Ide = np.eye(de)
    A_ub = np.vstack([np.hstack([Ide, -Ide]), np.hstack([-Ide, -Ide])])
    A_eq = np.hstack([D, np.zeros((n, de))])
    bounds = [(None, None)] * de + [(0.0, None)] * de
    r = linprog(c, A_ub=A_ub, b_ub=np.zeros(2 * de), A_eq=A_eq, b_eq=b,
                bounds=bounds, method='highs')
    if r.status != 0:
        return float('inf'), None
    u = r.x[:de]
    return float(np.abs(u).sum()), u


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument('--model', required=True, choices=list(MODELS))
    p.add_argument('--x', type=float, required=True, help='p1 value')
    p.add_argument('--y', type=float, required=True, help='p2 value')
    p.add_argument('--de', type=int, default=4, choices=[4, 6],
                   help='d_ext_single (frame width); D has de**2 columns')
    p.add_argument('--in_dir', type=str, default='results_trotter_v3')
    p.add_argument('--out', type=str, default=None)
    args = p.parse_args()

    model = MODELS[args.model]
    ix = int(np.argmin(np.abs(np.array(model.p1_vals) - args.x)))
    iy = int(np.argmin(np.abs(np.array(model.p2_vals) - args.y)))
    p1, p2 = float(model.p1_vals[ix]), float(model.p2_vals[iy])
    if abs(p1 - args.x) > 1e-6 or abs(p2 - args.y) > 1e-6:
        print(f'note: requested ({args.x},{args.y}) -> nearest grid point '
              f'({p1},{p2}) [ix={ix}, iy={iy}]', flush=True)

    f = Path(args.in_dir) / model.name / f'pt_{ix:03d}_{iy:03d}.npz'
    if not f.exists():
        sys.exit(f'ERROR: {f} not found')
    z = np.load(f, allow_pickle=True)
    S = np.asarray(z[f'opt_S_{args.de}'], dtype=float)
    dt, dim = float(z['dt']), int(z['dim'])
    stored = float(z[f'opt_fra_{args.de}'])
    conf = float(z[f'conf_fra_{args.de}']) if f'conf_fra_{args.de}' in z.files else None
    z.close()

    H1, H2, j1, j2 = model.build(p1, p2)
    G = bond_trotter_gate(H1, H2, j1, j2, dim, dt)
    D = _kron_power(S, 2)
    B = G.real.T @ D                                   # framability targets

    de_tot = D.shape[1]
    norms = np.empty(de_tot)
    us = [None] * de_tot
    for j in range(de_tot):
        norms[j], us[j] = column_gauge(D, B[:, j])
    jstar = int(np.nanargmax(np.where(np.isfinite(norms), norms, -np.inf)))
    framability = float(norms[jstar])
    ustar = us[jstar]

    # ---------------------------------------------------------------- LaTeX ---
    L = []
    L.append('% Auto-generated by scripts/export_framability_tex.py')
    L.append('\\documentclass[10pt]{article}')
    L.append('\\usepackage{amsmath,amssymb}')
    L.append('\\usepackage[a3paper,landscape,margin=8mm]{geometry}')
    L.append('\\usepackage{graphicx}')
    L.append('\\allowdisplaybreaks')
    L.append('\\begin{document}\\pagestyle{empty}')
    L.append(f'\\section*{{Framability of {model.name} at '
             f'$({model.p1_name},{model.p2_name})=({p1:g},{p2:g})$, '
             f'$d_{{\\rm ext}}={args.de}$}}')
    L.append(f'Grid point (ix,iy)=({ix},{iy}), $\\Delta t={dt:g}$, gate '
             f'$G=\\exp(L\\,\\Delta t)$ (real, $16\\times16$, Pauli basis). '
             f'Spectral floor $\\rho(G)={spectral_floor(G):.6f}$. '
             f'Stored $\\mathrm{{opt\\_fra}}={stored:.6f}$'
             + (f', confirmed $={conf:.6f}$' if conf is not None else '')
             + f'; recomputed here $={framability:.6f}$.\\par\\medskip')

    L.append('\\paragraph{Definition.} With $D=S\\otimes S$ and $B=G^{T}D$,')
    L.append('\\[ \\mathrm{framability}=\\max_j \\gamma_D(B_{:,j}), '
             '\\qquad \\gamma_D(b)=\\min\\{\\,\\|u\\|_1 : D\\,u=b\\,\\}. \\]')

    L.append(f'\\paragraph{{Frame $S$ ($4\\times{args.de}$).}}')
    L.append('\\[ S=' + bmatrix(S) + ' \\]')

    L.append(f'\\paragraph{{Dictionary $D=S\\otimes S$ ($16\\times{de_tot}$).}}')
    L.append('\\[\\resizebox{\\textwidth}{!}{$ D=' + bmatrix(D) + ' $}\\]')

    L.append('\\paragraph{Gate $G$ ($16\\times16$).}')
    L.append('\\[\\resizebox{\\textwidth}{!}{$ G=' + bmatrix(G) + ' $}\\]')

    L.append(f'\\paragraph{{Frame images $B=G^{{T}}D$ ($16\\times{de_tot}$).}} '
             'These are the targets whose atomic norms are computed; '
             'the transpose matches the reference evaluator '
             '($Y=G^{T}D$ in \\texttt{\\_framability\\_lp}).')
    L.append('\\[\\resizebox{\\textwidth}{!}{$ B=' + bmatrix(B) + ' $}\\]')

    L.append('\\paragraph{Per-column atomic norms $\\gamma_D(B_{:,j})$.}')
    L.append('\\[\\begin{array}{r|' + 'c' * de_tot + '}')
    L.append('j & ' + ' & '.join(str(j) for j in range(de_tot)) + ' \\\\ \\hline')
    L.append('\\gamma_D(B_{:,j}) & '
             + ' & '.join(('\\infty' if not np.isfinite(v) else f'{v:.4f}')
                          for v in norms) + ' \\\\')
    L.append('\\end{array}\\]')
    L.append(f'The maximum is attained at $j^\\star={jstar}$, so '
             f'$\\mathrm{{framability}}=\\gamma_D(B_{{:,{jstar}}})={framability:.6f}$.')

    if ustar is not None:
        L.append(f'\\paragraph{{Binding column $j^\\star={jstar}$: optimal '
                 'coefficients $u^\\star$.}} They satisfy $D\\,u^\\star=B_{:,'
                 f'{jstar}}}$ and $\\|u^\\star\\|_1='
                 f'{np.abs(ustar).sum():.6f}$.')
        L.append('\\[ u^\\star{}^{T}=' + bmatrix([ustar]) + ' \\]')
        resid = float(np.linalg.norm(D @ ustar - B[:, jstar]))
        L.append(f'Check: $\\|D\\,u^\\star-B_{{:,{jstar}}}\\|_2={resid:.2e}$ '
                 f'and $\\sum_k|u^\\star_k|={np.abs(ustar).sum():.6f}$, '
                 'reproducing the framability above.')

    L.append('\\end{document}')

    out = Path(args.out) if args.out else Path(
        f'framability_{model.name}_{p1:g}_{p2:g}_d{args.de}.tex')
    out.write_text('\n'.join(L), encoding='utf-8')
    print(f'[saved] {out}   framability={framability:.6f} '
          f'(stored {stored:.6f})', flush=True)


if __name__ == '__main__':
    main()
